version: '2'
services:
    testjh-app:
        image: testjh
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://testjh-mysql:3306/testjh?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testjh-mysql:
        extends:
            file: mysql.yml
            service: testjh-mysql
